# Generated by Django 5.1.3 on 2024-11-29 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_page', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('HTC', 'HTC')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone & Tablets', 'Phone & Tablets'), ('Cases & Covers', 'Cases & Covers'), ('Screen Guards', 'Screen Guards'), ('Cables & Chargers', 'Cables & Chargers'), ('Power Banks', 'Power Banks')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Optional title for the body image', max_length=100000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('HOCO', 'HOCO'), ('Nillkin', 'Nillkin'), ('Remax', 'Remax'), ('Baseus', 'Baseus')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='shop_page.color'),
        ),
    ]
