# Generated by Django 5.1.3 on 2024-11-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_page', '0004_color_rename_title_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('HTC', 'HTC'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone & Tablets', 'Phone & Tablets'), ('Cases & Covers', 'Cases & Covers'), ('Screen Guards', 'Screen Guards'), ('Cables & Chargers', 'Cables & Chargers'), ('Power Banks', 'Power Banks'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('HOCO', 'HOCO'), ('Nillkin', 'Nillkin'), ('Remax', 'Remax'), ('Baseus', 'Baseus'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
